version: '3'

services:
  # Database
  db:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcd1234
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wordpress_network
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3003:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: abcd1234 
    networks:
      - wordpress_network
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8003:80'
    restart: always
    volumes: 
      - './wordpress:/var/www/html'
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini 
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wordpress_network
networks:
  wordpress_network:
volumes:
  db_data: